// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using jeudontonestlehero.Core.Data.Models;

namespace jeudontonestlehero.Core.Data.Migrations
{
    [DbContext(typeof(DefaultDBContext))]
    [Migration("20200328101220_MiseAJourDesClasses")]
    partial class MiseAJourDesClasses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("jeudontonestlehero.Core.Data.Models.Aventure", b =>
                {
                    b.Property<int>("AventureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeAventure")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AventureId");

                    b.ToTable("Aventure");
                });

            modelBuilder.Entity("jeudontonestlehero.Core.Data.Models.Paragraphe", b =>
                {
                    b.Property<int>("ParagrapheID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("maQuestionQuestionId")
                        .HasColumnType("int");

                    b.HasKey("ParagrapheID");

                    b.HasIndex("maQuestionQuestionId");

                    b.ToTable("Paragraphe");
                });

            modelBuilder.Entity("jeudontonestlehero.Core.Data.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("jeudontonestlehero.Core.Data.Models.Reponse", b =>
                {
                    b.Property<int>("ReponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("ReponseId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Reponse");
                });

            modelBuilder.Entity("jeudontonestlehero.Core.Data.Models.Paragraphe", b =>
                {
                    b.HasOne("jeudontonestlehero.Core.Data.Models.Question", "maQuestion")
                        .WithMany()
                        .HasForeignKey("maQuestionQuestionId");
                });

            modelBuilder.Entity("jeudontonestlehero.Core.Data.Models.Reponse", b =>
                {
                    b.HasOne("jeudontonestlehero.Core.Data.Models.Question", null)
                        .WithMany("MesReponses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
